import { Content } from "./Content";

export interface Section {
    type: string;
    id: string;
    identifier: string;
    undestroyable: boolean;
    title: string;
    slug:string;
    body: string;
    meta_title: string;
    meta_description: string;
    meta_keywords: string;
    google_analytics_id: string;
    google_tag_manager_id: string;
    google_site_verification: string;
    legacy_id: number;
    background_color: string;
    is_external: boolean;
    external_link: any[];
    have_unique_content: boolean;
    fetched_content_limit: null;
    limited_access_login: null;
    limited_access_password: null;
    limited_access_text: null;
    external_scripts: null;
    custom_css: null;
    informations: null;
    content_types: any[];
    only_future_content: boolean;
    only_past_content: boolean;
    date_filter_begin_at: string;
    date_filter_end_at: string;
    date_filter_field: string;
    content_order: string;
    status: "published" | "unpublished";
    position: number;
    date_timeline_begin_at: string;
    date_timeline_end_at: string;
    social_network_urls: string;
    created_at: string;
    updated_at:string;
    finder_digest: string;
    social_network_secrets: null;
    ticketing_url: null;
    ignore_slug: boolean;
    default_og_image: '';
    project_name: string;
    project: {};
    parent: any;
    section_template: string;
    children: Section[];
    contents: Content[];
    tags: any[];
    main_image: string;
    background_image: string;
    canonical_rewrites: any[];
    relationshipNames: any[]
}